window.PROPERTIES = [
  {
    id: "GV-1001",
    titulo: "Apartamento moderno en Valle del Lili",
    precio: 1850000,
    tipoOperacion: "arriendo",
    tipoInmueble: "Apartamento",
    barrio: "Valle del Lili",
    direccionCorta: "Valle del Lili, Cali",
    areaM2: 72,
    habitaciones: 3,
    banos: 2,
    parqueadero: 1,
    estrato: 5,
    destacado: true,
    nuevo: true,
    lat: 3.3692,
    lng: -76.5338,
    imagenes: [
      { src: "./assets/placeholders/property-1.svg", alt: "Fachada del apartamento en Valle del Lili" },
      { src: "./assets/placeholders/property-2.svg", alt: "Sala del apartamento en Valle del Lili" },
      { src: "./assets/placeholders/property-3.svg", alt: "Habitación del apartamento en Valle del Lili" }
    ],
    descripcion: "Apartamento con excelente iluminación natural, balcón y zona social completa.",
    amenidades: ["Piscina", "Gimnasio", "Portería 24h", "Salón social"],
    codigo: "GV-AR-001"
  },
  {
    id: "GV-1002",
    titulo: "Casa familiar en Ciudad Jardín",
    precio: 4200000,
    tipoOperacion: "arriendo",
    tipoInmueble: "Casa",
    barrio: "Ciudad Jardín",
    direccionCorta: "Ciudad Jardín, Cali",
    areaM2: 220,
    habitaciones: 4,
    banos: 4,
    parqueadero: 2,
    estrato: 6,
    destacado: true,
    nuevo: false,
    lat: 3.3448,
    lng: -76.5403,
    imagenes: [
      { src: "./assets/placeholders/property-2.svg", alt: "Frente de casa en Ciudad Jardín" },
      { src: "./assets/placeholders/property-1.svg", alt: "Sala principal de la casa" },
      { src: "./assets/placeholders/property-3.svg", alt: "Patio interior de la casa" }
    ],
    descripcion: "Casa amplia en sector residencial premium, ideal para familias.",
    amenidades: ["Jardín", "Estudio", "Cuarto de servicio", "Zona BBQ"],
    codigo: "GV-AR-002"
  },
  {
    id: "GV-1003",
    titulo: "Apartamento en Bochalema con vista",
    precio: 1650000,
    tipoOperacion: "arriendo",
    tipoInmueble: "Apartamento",
    barrio: "Bochalema",
    direccionCorta: "Bochalema, Cali",
    areaM2: 64,
    habitaciones: 2,
    banos: 2,
    parqueadero: 1,
    estrato: 4,
    destacado: false,
    nuevo: true,
    lat: 3.3661,
    lng: -76.5417,
    imagenes: [
      { src: "./assets/placeholders/property-3.svg", alt: "Exterior de apartamento en Bochalema" },
      { src: "./assets/placeholders/property-1.svg", alt: "Cocina del apartamento en Bochalema" },
      { src: "./assets/placeholders/property-2.svg", alt: "Zona social del apartamento en Bochalema" }
    ],
    descripcion: "Apartamento con acabados contemporáneos y excelente conectividad.",
    amenidades: ["Ascensor", "Parque infantil", "Cancha múltiple", "Shut de basuras"],
    codigo: "GV-AR-003"
  },
  {
    id: "GV-1004",
    titulo: "Local comercial sobre vía principal",
    precio: 3900000,
    tipoOperacion: "arriendo",
    tipoInmueble: "Local",
    barrio: "Tequendama",
    direccionCorta: "Tequendama, Cali",
    areaM2: 98,
    habitaciones: 0,
    banos: 1,
    parqueadero: 0,
    estrato: 5,
    destacado: false,
    nuevo: false,
    lat: 3.4335,
    lng: -76.5387,
    imagenes: [
      { src: "./assets/placeholders/property-1.svg", alt: "Fachada local Tequendama" },
      { src: "./assets/placeholders/property-2.svg", alt: "Interior local Tequendama" },
      { src: "./assets/placeholders/property-3.svg", alt: "Vitrina local Tequendama" }
    ],
    descripcion: "Excelente vitrina comercial en zona de alto tráfico.",
    amenidades: ["Bahía de parqueo", "Alto flujo peatonal", "Cercano a estación MIO"],
    codigo: "GV-AR-004"
  },
  {
    id: "GV-1005",
    titulo: "Oficina corporativa en El Peñón",
    precio: 3100000,
    tipoOperacion: "arriendo",
    tipoInmueble: "Oficina",
    barrio: "El Peñón",
    direccionCorta: "El Peñón, Cali",
    areaM2: 86,
    habitaciones: 0,
    banos: 2,
    parqueadero: 1,
    estrato: 5,
    destacado: true,
    nuevo: false,
    lat: 3.4511,
    lng: -76.5395,
    imagenes: [
      { src: "./assets/placeholders/property-2.svg", alt: "Oficina en El Peñón vista general" },
      { src: "./assets/placeholders/property-3.svg", alt: "Sala de juntas en oficina" },
      { src: "./assets/placeholders/property-1.svg", alt: "Recepción de oficina" }
    ],
    descripcion: "Espacio corporativo con iluminación natural y zonas de trabajo abiertas.",
    amenidades: ["Recepción", "Aire acondicionado", "Parqueadero privado"],
    codigo: "GV-AR-005"
  },
  {
    id: "GV-1006",
    titulo: "Bodega funcional en Acopi",
    precio: 7600000,
    tipoOperacion: "arriendo",
    tipoInmueble: "Bodega",
    barrio: "Acopi",
    direccionCorta: "Acopi, Yumbo",
    areaM2: 420,
    habitaciones: 0,
    banos: 2,
    parqueadero: 2,
    estrato: 3,
    destacado: false,
    nuevo: true,
    lat: 3.5028,
    lng: -76.5079,
    imagenes: [
      { src: "./assets/placeholders/property-3.svg", alt: "Bodega en Acopi exterior" },
      { src: "./assets/placeholders/property-1.svg", alt: "Bodega en Acopi interior" },
      { src: "./assets/placeholders/property-2.svg", alt: "Zona de carga de bodega" }
    ],
    descripcion: "Bodega con excelente altura, fácil acceso logístico y zona de cargue.",
    amenidades: ["Altura libre", "Puerta camión", "Piso reforzado"],
    codigo: "GV-AR-006"
  },
  {
    id: "GV-2001",
    titulo: "Apartamento en venta en Valle del Lili",
    precio: 325000000,
    tipoOperacion: "venta",
    tipoInmueble: "Apartamento",
    barrio: "Valle del Lili",
    direccionCorta: "Valle del Lili, Cali",
    areaM2: 81,
    habitaciones: 3,
    banos: 2,
    parqueadero: 1,
    estrato: 5,
    destacado: true,
    nuevo: false,
    lat: 3.3718,
    lng: -76.5317,
    imagenes: [
      { src: "./assets/placeholders/property-1.svg", alt: "Apartamento en venta Valle del Lili fachada" },
      { src: "./assets/placeholders/property-2.svg", alt: "Apartamento en venta Valle del Lili sala" },
      { src: "./assets/placeholders/property-3.svg", alt: "Apartamento en venta Valle del Lili cocina" }
    ],
    descripcion: "Apartamento con acabados premium y ubicación estratégica.",
    amenidades: ["Piscina", "Zona infantil", "Salón social", "Portería 24h"],
    codigo: "GV-VE-001"
  },
  {
    id: "GV-2002",
    titulo: "Casa campestre en Pance",
    precio: 980000000,
    tipoOperacion: "venta",
    tipoInmueble: "Casa",
    barrio: "Pance",
    direccionCorta: "Pance, Cali",
    areaM2: 320,
    habitaciones: 4,
    banos: 5,
    parqueadero: 3,
    estrato: 6,
    destacado: true,
    nuevo: true,
    lat: 3.3342,
    lng: -76.5584,
    imagenes: [
      { src: "./assets/placeholders/property-2.svg", alt: "Casa campestre en Pance exterior" },
      { src: "./assets/placeholders/property-3.svg", alt: "Casa campestre en Pance sala" },
      { src: "./assets/placeholders/property-1.svg", alt: "Casa campestre en Pance jardín" }
    ],
    descripcion: "Casa de alto perfil con diseño abierto y amplias zonas verdes.",
    amenidades: ["Piscina privada", "Terraza", "Zona BBQ", "Estudio"],
    codigo: "GV-VE-002"
  },
  {
    id: "GV-2003",
    titulo: "Local en venta en San Fernando",
    precio: 420000000,
    tipoOperacion: "venta",
    tipoInmueble: "Local",
    barrio: "San Fernando",
    direccionCorta: "San Fernando, Cali",
    areaM2: 112,
    habitaciones: 0,
    banos: 2,
    parqueadero: 0,
    estrato: 5,
    destacado: false,
    nuevo: false,
    lat: 3.4321,
    lng: -76.5463,
    imagenes: [
      { src: "./assets/placeholders/property-3.svg", alt: "Local en venta San Fernando vista externa" },
      { src: "./assets/placeholders/property-1.svg", alt: "Local en venta San Fernando interior" },
      { src: "./assets/placeholders/property-2.svg", alt: "Local en venta San Fernando zona de vitrina" }
    ],
    descripcion: "Local comercial en corredor de alta demanda.",
    amenidades: ["Alto tráfico", "Esquinero", "Fácil acceso"],
    codigo: "GV-VE-003"
  },
  {
    id: "GV-2004",
    titulo: "Oficina en venta en Santa Mónica",
    precio: 510000000,
    tipoOperacion: "venta",
    tipoInmueble: "Oficina",
    barrio: "Santa Mónica",
    direccionCorta: "Santa Mónica, Cali",
    areaM2: 126,
    habitaciones: 0,
    banos: 2,
    parqueadero: 2,
    estrato: 5,
    destacado: false,
    nuevo: true,
    lat: 3.4716,
    lng: -76.5312,
    imagenes: [
      { src: "./assets/placeholders/property-1.svg", alt: "Oficina Santa Mónica exterior" },
      { src: "./assets/placeholders/property-2.svg", alt: "Oficina Santa Mónica interior" },
      { src: "./assets/placeholders/property-3.svg", alt: "Oficina Santa Mónica puestos de trabajo" }
    ],
    descripcion: "Oficina lista para operación, ideal para empresas en crecimiento.",
    amenidades: ["Ascensor", "Parqueadero", "Seguridad"],
    codigo: "GV-VE-004"
  },
  {
    id: "GV-2005",
    titulo: "Bodega en venta en Yumbo industrial",
    precio: 1350000000,
    tipoOperacion: "venta",
    tipoInmueble: "Bodega",
    barrio: "Yumbo Industrial",
    direccionCorta: "Yumbo Industrial, Yumbo",
    areaM2: 780,
    habitaciones: 0,
    banos: 3,
    parqueadero: 4,
    estrato: 3,
    destacado: true,
    nuevo: false,
    lat: 3.5503,
    lng: -76.4907,
    imagenes: [
      { src: "./assets/placeholders/property-2.svg", alt: "Bodega Yumbo vista exterior" },
      { src: "./assets/placeholders/property-3.svg", alt: "Bodega Yumbo área de almacenamiento" },
      { src: "./assets/placeholders/property-1.svg", alt: "Bodega Yumbo área de maniobra" }
    ],
    descripcion: "Activo industrial de alto potencial para logística y almacenamiento.",
    amenidades: ["Muelles de carga", "Energía trifásica", "Vigilancia"],
    codigo: "GV-VE-005"
  },
  {
    id: "GV-2006",
    titulo: "Apartamento en venta en Caney",
    precio: 298000000,
    tipoOperacion: "venta",
    tipoInmueble: "Apartamento",
    barrio: "Caney",
    direccionCorta: "Caney, Cali",
    areaM2: 76,
    habitaciones: 3,
    banos: 2,
    parqueadero: 1,
    estrato: 4,
    destacado: false,
    nuevo: true,
    lat: 3.3812,
    lng: -76.533,
    imagenes: [
      { src: "./assets/placeholders/property-3.svg", alt: "Apartamento Caney fachada" },
      { src: "./assets/placeholders/property-1.svg", alt: "Apartamento Caney sala comedor" },
      { src: "./assets/placeholders/property-2.svg", alt: "Apartamento Caney habitación" }
    ],
    descripcion: "Excelente distribución interior y ubicación cerca de vías principales.",
    amenidades: ["Zona infantil", "Piscina", "Parqueadero visitante"],
    codigo: "GV-VE-006"
  }
];
