(function () {
  var PLACEHOLDER =
    "data:image/svg+xml;utf8," +
    encodeURIComponent(
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 400">' +
        '<rect width="640" height="400" fill="#e8edf4"/>' +
        '<path d="M80 305h480L440 165l-76 72-72-81-96 102-44-40z" fill="#c8d5e4"/>' +
        '<circle cx="470" cy="122" r="28" fill="#d9e5f1"/>' +
      "</svg>"
    );

  window.listings = [
    {
      id: "fr-193266756",
      titulo: "Casa en venta en Villa del Sol",
      precio: 240000000,
      barrio: "Villa del Sol",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: 4,
      banos: 2,
      areaM2: 110,
      parqueadero: null,
      estrato: 4,
      tipo: "casa",
      operacion: "venta",
      destacado: true,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "FincaRaiz",
      sourceUrl: "https://www.fincaraiz.com.co/detalle/casa-en-venta/villa-del-sol/cali/193266756"
    },
    {
      id: "fr-192223798",
      titulo: "Local en arriendo en Pance",
      precio: 7000000,
      barrio: "Pance",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: null,
      banos: null,
      areaM2: 50,
      parqueadero: null,
      estrato: 6,
      tipo: "local",
      operacion: "arriendo",
      destacado: false,
      nuevo: true,
      imagen: PLACEHOLDER,
      source: "FincaRaiz",
      sourceUrl: "https://www.fincaraiz.com.co/detalle/local-en-arriendo/pance/cali/192223798"
    },
    {
      id: "fr-192337861",
      titulo: "Local en arriendo en Pance",
      precio: 14000000,
      barrio: "Pance",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: null,
      banos: 1,
      areaM2: 300,
      parqueadero: null,
      estrato: 6,
      tipo: "local",
      operacion: "arriendo",
      destacado: true,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "FincaRaiz",
      sourceUrl: "https://www.fincaraiz.com.co/detalle/local-en-arriendo/pance/cali/192337861"
    },
    {
      id: "fr-192223803",
      titulo: "Local en arriendo en Pance",
      precio: 3600000,
      barrio: "Pance",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: null,
      banos: null,
      areaM2: 25,
      parqueadero: null,
      estrato: 6,
      tipo: "local",
      operacion: "arriendo",
      destacado: false,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "FincaRaiz",
      sourceUrl: "https://www.fincaraiz.com.co/detalle/local-en-arriendo/pance/cali/192223803"
    },
    {
      id: "fr-11110906",
      titulo: "Lote en venta en Prados del Norte",
      precio: 750000000,
      barrio: "Prados del Norte",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: null,
      banos: null,
      areaM2: 384,
      parqueadero: null,
      estrato: 5,
      tipo: "lote",
      operacion: "venta",
      destacado: false,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "FincaRaiz",
      sourceUrl: "https://www.fincaraiz.com.co/detalle/lote-en-venta/prados-del-norte/cali/11110906"
    },
    {
      id: "fr-193338250",
      titulo: "Casa campestre en venta en Arroyohondo",
      precio: 1820000000,
      barrio: "Arroyohondo",
      direccionCorta: "Yumbo, Valle del Cauca",
      habitaciones: 4,
      banos: 4,
      areaM2: 270,
      parqueadero: 6,
      estrato: 6,
      tipo: "casa",
      operacion: "venta",
      destacado: true,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "FincaRaiz",
      sourceUrl: "https://www.fincaraiz.com.co/detalle/casa-campestre-en-venta/arroyohondo/yumbo/193338250"
    },
    {
      id: "fr-193338267",
      titulo: "Casa en venta en San Fernando Viejo",
      precio: 1200000000,
      barrio: "San Fernando Viejo",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: 8,
      banos: 5,
      areaM2: 392,
      parqueadero: 3,
      estrato: 5,
      tipo: "casa",
      operacion: "venta",
      destacado: false,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "FincaRaiz",
      sourceUrl: "https://www.fincaraiz.com.co/detalle/casa-en-venta/san-fernando-viejo/cali/193338267"
    },
    {
      id: "mc-M5454816",
      titulo: "Lote en venta en Prados del Norte",
      precio: 750000000,
      barrio: "Prados del Norte",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: null,
      banos: null,
      areaM2: 384,
      parqueadero: null,
      estrato: 5,
      tipo: "lote",
      operacion: "venta",
      destacado: false,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "Metrocuadrado",
      sourceUrl: "https://www.metrocuadrado.com/inmueble/venta-lote-urbano-cali-prados-del-norte/18346-M5454816"
    },
    {
      id: "mc-M5811442",
      titulo: "Casa en venta en Capri",
      precio: 240000000,
      barrio: "Capri",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: 3,
      banos: 3,
      areaM2: 100,
      parqueadero: null,
      estrato: 5,
      tipo: "casa",
      operacion: "venta",
      destacado: false,
      nuevo: true,
      imagen: PLACEHOLDER,
      source: "Metrocuadrado",
      sourceUrl: "https://www.metrocuadrado.com/inmueble/venta-casa-cali-capri-3-habitaciones-3-banos/18346-M5811442"
    },
    {
      id: "mc-M5730859",
      titulo: "Local en arriendo en Pance",
      precio: 14000000,
      barrio: "Pance",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: null,
      banos: 1,
      areaM2: 300,
      parqueadero: null,
      estrato: 6,
      tipo: "local",
      operacion: "arriendo",
      destacado: true,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "Metrocuadrado",
      sourceUrl: "https://www.metrocuadrado.com/inmueble/arriendo-local-comercial-cali-pance/18346-M5730859"
    },
    {
      id: "mc-M5676069",
      titulo: "Local en arriendo en Pance",
      precio: 3600000,
      barrio: "Pance",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: null,
      banos: null,
      areaM2: 25,
      parqueadero: null,
      estrato: 6,
      tipo: "local",
      operacion: "arriendo",
      destacado: false,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "Metrocuadrado",
      sourceUrl: "https://www.metrocuadrado.com/inmueble/arriendo-local-comercial-cali-pance/18346-M5676069"
    },
    {
      id: "cc-3591531",
      titulo: "Apartamento en venta en Ciudad Real",
      precio: 220000000,
      barrio: "Ciudad Real",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: 2,
      banos: 2,
      areaM2: 53,
      parqueadero: null,
      estrato: 4,
      tipo: "apartamento",
      operacion: "venta",
      destacado: false,
      nuevo: true,
      imagen: PLACEHOLDER,
      source: "Ciencuadras",
      sourceUrl: "https://www.ciencuadras.com/venta/apartamento/cali/ciudad-real/3591531"
    },
    {
      id: "cc-3339498",
      titulo: "Edificio en venta en Caney",
      precio: 649000000,
      barrio: "Caney",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: 6,
      banos: 5,
      areaM2: 270,
      parqueadero: 2,
      estrato: 4,
      tipo: "edificio",
      operacion: "venta",
      destacado: true,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "Ciencuadras",
      sourceUrl: "https://www.ciencuadras.com/venta/edificio/cali/caney/3339498"
    },
    {
      id: "cc-3397195",
      titulo: "Apartamento en venta en Camino Real",
      precio: 230000000,
      barrio: "Camino Real",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: 3,
      banos: 1,
      areaM2: 64,
      parqueadero: 1,
      estrato: 4,
      tipo: "apartamento",
      operacion: "venta",
      destacado: false,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "Ciencuadras",
      sourceUrl: "https://www.ciencuadras.com/venta/apartamento/cali/camino-real/3397195"
    },
    {
      id: "cc-3306872",
      titulo: "Apartamento en venta en Militar",
      precio: 300000000,
      barrio: "Militar",
      direccionCorta: "Cali, Valle del Cauca",
      habitaciones: 3,
      banos: 2,
      areaM2: 76,
      parqueadero: 1,
      estrato: 4,
      tipo: "apartamento",
      operacion: "venta",
      destacado: false,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "Ciencuadras",
      sourceUrl: "https://www.ciencuadras.com/venta/apartamento/cali/militar/3306872"
    },
    {
      id: "cc-3339496",
      titulo: "Edificio en venta en Jamundí",
      precio: 900000000,
      barrio: "Jamundí",
      direccionCorta: "Jamundí, Valle del Cauca",
      habitaciones: 20,
      banos: 10,
      areaM2: 500,
      parqueadero: 3,
      estrato: 6,
      tipo: "edificio",
      operacion: "venta",
      destacado: true,
      nuevo: false,
      imagen: PLACEHOLDER,
      source: "Ciencuadras",
      sourceUrl: "https://www.ciencuadras.com/venta/edificio/jamundi/jamundi/3339496"
    }
  ];
})();
