const PROPERTIES = [
  { id: 1, titulo: 'Apartamento moderno en Ciudad Jardín', gestion: 'arriendo', ciudad: 'Cali', zona: 'Ciudad Jardín', tipo: 'Apartamento', precio: 3200000, habitaciones: 3, banos: 2, area: 98, imagen: 'https://placehold.co/800x520?text=Ciudad+Jardin', codigo: 'GV-1001' },
  { id: 2, titulo: 'Casa familiar en Pance', gestion: 'arriendo', ciudad: 'Cali', zona: 'Pance', tipo: 'Casa', precio: 4800000, habitaciones: 4, banos: 4, area: 220, imagen: 'https://placehold.co/800x520?text=Pance', codigo: 'GV-1002' },
  { id: 3, titulo: 'Apto ejecutivo en Granada', gestion: 'arriendo', ciudad: 'Cali', zona: 'Granada', tipo: 'Apartamento', precio: 2900000, habitaciones: 2, banos: 2, area: 82, imagen: 'https://placehold.co/800x520?text=Granada', codigo: 'GV-1003' },
  { id: 4, titulo: 'Local comercial en San Fernando', gestion: 'arriendo', ciudad: 'Cali', zona: 'San Fernando', tipo: 'Local', precio: 3500000, habitaciones: 0, banos: 1, area: 76, imagen: 'https://placehold.co/800x520?text=San+Fernando', codigo: 'GV-1004' },
  { id: 5, titulo: 'Apartamento con balcón en Valle del Lili', gestion: 'arriendo', ciudad: 'Cali', zona: 'Valle del Lili', tipo: 'Apartamento', precio: 2100000, habitaciones: 2, banos: 2, area: 74, imagen: 'https://placehold.co/800x520?text=Valle+del+Lili', codigo: 'GV-1005' },
  { id: 6, titulo: 'Casa campestre en Jamundí', gestion: 'venta', ciudad: 'Jamundí', zona: 'Alfaguara', tipo: 'Casa', precio: 690000000, habitaciones: 4, banos: 5, area: 300, imagen: 'https://placehold.co/800x520?text=Alfaguara', codigo: 'GV-1006' },
  { id: 7, titulo: 'Apartamento en Bochalema', gestion: 'venta', ciudad: 'Cali', zona: 'Bochalema', tipo: 'Apartamento', precio: 420000000, habitaciones: 3, banos: 2, area: 96, imagen: 'https://placehold.co/800x520?text=Bochalema', codigo: 'GV-1007' },
  { id: 8, titulo: 'Oficina premium en Santa Mónica', gestion: 'arriendo', ciudad: 'Cali', zona: 'Santa Mónica', tipo: 'Oficina', precio: 5100000, habitaciones: 0, banos: 2, area: 110, imagen: 'https://placehold.co/800x520?text=Santa+Monica', codigo: 'GV-1008' },
  { id: 9, titulo: 'Casa esquinera en La Flora', gestion: 'venta', ciudad: 'Cali', zona: 'La Flora', tipo: 'Casa', precio: 780000000, habitaciones: 4, banos: 3, area: 260, imagen: 'https://placehold.co/800x520?text=La+Flora', codigo: 'GV-1009' },
  { id: 10, titulo: 'Apartamento en Ciudad Pacífica', gestion: 'arriendo', ciudad: 'Cali', zona: 'Ciudad Pacífica', tipo: 'Apartamento', precio: 1750000, habitaciones: 2, banos: 2, area: 68, imagen: 'https://placehold.co/800x520?text=Ciudad+Pacifica', codigo: 'GV-1010' },
  { id: 11, titulo: 'Lote residencial en Jamundí', gestion: 'venta', ciudad: 'Jamundí', zona: 'Sachamate', tipo: 'Lote', precio: 260000000, habitaciones: 0, banos: 0, area: 540, imagen: 'https://placehold.co/800x520?text=Sachamate', codigo: 'GV-1011' },
  { id: 12, titulo: 'Penthouse en El Peñón', gestion: 'venta', ciudad: 'Cali', zona: 'El Peñón', tipo: 'Apartamento', precio: 980000000, habitaciones: 3, banos: 4, area: 210, imagen: 'https://placehold.co/800x520?text=El+Penon', codigo: 'GV-1012' },
  { id: 13, titulo: 'Apartamento familiar en Tequendama', gestion: 'arriendo', ciudad: 'Cali', zona: 'Tequendama', tipo: 'Apartamento', precio: 2600000, habitaciones: 3, banos: 2, area: 90, imagen: 'https://placehold.co/800x520?text=Tequendama', codigo: 'GV-1013' },
  { id: 14, titulo: 'Casa de lujo en Pance', gestion: 'venta', ciudad: 'Cali', zona: 'Pance', tipo: 'Casa', precio: 1450000000, habitaciones: 5, banos: 6, area: 460, imagen: 'https://placehold.co/800x520?text=Pance+Luxury', codigo: 'GV-1014' }
];
